fruits = []
f1 = input("Enter the fruits: \n")
fruits.append(f1)
f2 = input("Enter the fruits: \n")
fruits.append(f2)
f3 = input("Enter the fruits: \n")
fruits.append(f3)
f4 = input("Enter the fruits: \n")
fruits.append(f4)
f5 = input("Enter the fruits: \n")
fruits.append(f5)
f6 = input("Enter the fruits: \n")
fruits.append(f6)
f7 = input("Enter the fruits: \n")
fruits.append(f7)
f8 = input("Enter the fruits: \n")
fruits.append(f8)
print (fruits)