s = set()
n = input("Enter the number:\n")
s.add(int(n))
n = input("Enter the number:\n")
s.add(int(n))
n = input("Enter the number:\n")
s.add(int(n))
n = input("Enter the number:\n")
s.add(int(n))
n = input("Enter the number:\n")
s.add(int(n))
n = input("Enter the number:\n")
s.add(int(n))
n = input("Enter the number:\n")
s.add(int(n))
n = input("Enter the number:\n")
s.add(int(n))
print(s)

